In [5]:


print("hello world")

hello world


In [6]:
age=int(input("enter age"))
if age>=10:
    print("man")
else:
    print("no")

no


In [7]:
age=int(input("enter age"))
status="adult" if age>=18 else ("dede party invite ")
print(f"u are an {status}")


u are an adult


In [8]:
a=int(input("1st num"))
b=int(input("2nd num"))
ope=input("enter operator")
if ope=="+":
    
     print("sum=",a+b)

    
elif ope=="-": 
      print("diff is:",a-b)
elif ope=="*" :
    print("product is:",a*b)      

ValueError: invalid literal for int() with base 10: ''

In [9]:
fruits = ["banana", "apple", "cherry"]
fruits.sort()
print(fruits)


['apple', 'banana', 'cherry']


In [10]:
a = [1, 2, 3]
b = [4, 5, 6]
c=a+b
print(c)


[1, 2, 3, 4, 5, 6]


In [11]:

numbers = [5, 2, 9, 1, 7]

numbers.extend([3,4,5,6,2])
print(numbers)


[5, 2, 9, 1, 7, 3, 4, 5, 6, 2]


In [12]:
numbers=[3,4,5,6,7]
numbers[0]=1
print(numbers)

[1, 4, 5, 6, 7]


In [13]:
import numpy as np
b=np.array([1,2,3,4])
print(b)
type(b)
a=b[1:3]
print(a)
print(b)

[1 2 3 4]
[2 3]
[1 2 3 4]


In [14]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
arr.ndim
arr[:, 1]      # all rows, column 1 → [2, 5]
arr[0, :]      # row 0, all columns → [1, 2, 3]
arr[0:2, 1:3]  # rows 0-1, columns 1-2


[2 3]


array([[2, 3],
       [6, 7]])

In [15]:
import numpy as np

arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(arr)
print("Shape:", arr.shape)
print(arr[1][1][0])
reshaped = arr.reshape(3, 4)
print(reshaped)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
10
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
row_vector = a[:np.newaxis]
row_vector.shape

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
a2 = a[np.newaxis, :]
print(a2.shape)
print(a2)


In [ ]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Ram', None, 'Eva'],
    'Age': [25, 30, None, 34, 22, 28],
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Kathmandu', 'Chicago', 'Houston'],
    'Occupation': ['Engineer', 'Artist', 'Doctor', 'Teacher', 'Developer', 'Designer'],
    'Marital Status': ['Single', 'Married', 'Single', 'Married', 'Single', 'Single']
}

df = pd.DataFrame(data)
df

In [23]:
import pandas as pd
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [24]:

data={
    'Name': ['Alice', 'Bob', 'Charlie', 'Ram', None, 'Eva'],
    'Age': [25, 30, None, 34, 22, 28],
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Kathmandu', 'Chicago', 'Houston'],
    'Occupation': ['Engineer', 'Artist', 'Doctor', 'Teacher', 'Developer', 'Designer'],
    'Marital Status': ['Single', 'Married', 'Single', 'Married', 'Single', 'Single']
}
df=pd.DataFrame(data)
df.head()


,Name,Age,City,Occupation,Marital Status
0,Alice,25.0,New York,Engineer,Single
1,Bob,30.0,San Francisco,Artist,Married
2,Charlie,NaN,Los Angeles,Doctor,Single
3,Ram,34.0,Kathmandu,Teacher,Married
4,None,22.0,Chicago,Developer,Single


In [25]:
df.to_csv('output.csv', index=False)

In [26]:
d = pd.read_csv('output.csv')
d

,Name,Age,City,Occupation,Marital Status
0,Alice,25.0,New York,Engineer,Single
1,Bob,30.0,San Francisco,Artist,Married
2,Charlie,NaN,Los Angeles,Doctor,Single
3,Ram,34.0,Kathmandu,Teacher,Married
4,NaN,22.0,Chicago,Developer,Single
5,Eva,28.0,Houston,Designer,Single


In [27]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Name            5 non-null      object 
 1   Age             5 non-null      float64
 2   City            6 non-null      object 
 3   Occupation      6 non-null      object 
 4   Marital Status  6 non-null      object 
dtypes: float64(1), object(4)
memory usage: 372.0+ bytes


In [28]:
df.describe()

,Age
count,5.000000
mean,27.800000
std,4.604346
min,22.000000
25%,25.000000
50%,28.000000
75%,30.000000
max,34.000000


In [29]:
sorted_rows_df = df.sort_values(by='Name', ascending=True)
sorted_rows_df

,Name,Age,City,Occupation,Marital Status
0,Alice,25.0,New York,Engineer,Single
1,Bob,30.0,San Francisco,Artist,Married
2,Charlie,NaN,Los Angeles,Doctor,Single
5,Eva,28.0,Houston,Designer,Single
3,Ram,34.0,Kathmandu,Teacher,Married
4,None,22.0,Chicago,Developer,Single


In [30]:
ages = df['Age']
print(ages)

0    25.0
1    30.0
2     NaN
3    34.0
4    22.0
5    28.0
Name: Age, dtype: float64
